/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef model_TYPES_H
#define model_TYPES_H

#include <Thrift.h>
#include <TApplicationException.h>
#include <protocol/TProtocol.h>
#include <transport/TTransport.h>



namespace rpc {

struct e_job_state {
  enum type {
    WAITING = 0,
    RUNNING = 1,
    SUCCEDED = 2,
    FAILED = 3
  };
};

extern const std::map<int, const char*> _e_job_state_VALUES_TO_NAMES;

typedef int16_t integer;

typedef std::vector<integer>  v_job_ids;

typedef std::vector<class t_job>  v_jobs;

typedef struct _t_node__isset {
  _t_node__isset() : weight(false) {}
  bool weight;
} _t_node__isset;

class t_node {
 public:

  static const char* ascii_fingerprint; // = "5AC90DA6F2A44658D2CCBD1121C29A34";
  static const uint8_t binary_fingerprint[16]; // = {0x5A,0xC9,0x0D,0xA6,0xF2,0xA4,0x46,0x58,0xD2,0xCC,0xBD,0x11,0x21,0xC2,0x9A,0x34};

  t_node() : name(""), weight(0) {
  }

  virtual ~t_node() throw() {}

  std::string name;
  integer weight;

  _t_node__isset __isset;

  bool operator == (const t_node & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    if (__isset.weight != rhs.__isset.weight)
      return false;
    else if (__isset.weight && !(weight == rhs.weight))
      return false;
    return true;
  }
  bool operator != (const t_node &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const t_node & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _t_job__isset {
  _t_job__isset() : start_time(false), stop_time(false), return_code(false), prv(false), nxt(false) {}
  bool start_time;
  bool stop_time;
  bool return_code;
  bool prv;
  bool nxt;
} _t_job__isset;

class t_job {
 public:

  static const char* ascii_fingerprint; // = "833E26B080399F3EA767DBE2EC895541";
  static const uint8_t binary_fingerprint[16]; // = {0x83,0x3E,0x26,0xB0,0x80,0x39,0x9F,0x3E,0xA7,0x67,0xDB,0xE2,0xEC,0x89,0x55,0x41};

  t_job() : start_time(0), stop_time(0), return_code(0), id(0), name(""), node_name(""), domain(""), cmd_line(""), weight(0) {
  }

  virtual ~t_job() throw() {}

  int64_t start_time;
  int64_t stop_time;
  integer return_code;
  integer id;
  std::string name;
  std::string node_name;
  std::string domain;
  std::string cmd_line;
  integer weight;
  v_job_ids prv;
  v_job_ids nxt;

  _t_job__isset __isset;

  bool operator == (const t_job & rhs) const
  {
    if (__isset.start_time != rhs.__isset.start_time)
      return false;
    else if (__isset.start_time && !(start_time == rhs.start_time))
      return false;
    if (__isset.stop_time != rhs.__isset.stop_time)
      return false;
    else if (__isset.stop_time && !(stop_time == rhs.stop_time))
      return false;
    if (__isset.return_code != rhs.__isset.return_code)
      return false;
    else if (__isset.return_code && !(return_code == rhs.return_code))
      return false;
    if (!(id == rhs.id))
      return false;
    if (!(name == rhs.name))
      return false;
    if (!(node_name == rhs.node_name))
      return false;
    if (!(domain == rhs.domain))
      return false;
    if (!(cmd_line == rhs.cmd_line))
      return false;
    if (!(weight == rhs.weight))
      return false;
    if (__isset.prv != rhs.__isset.prv)
      return false;
    else if (__isset.prv && !(prv == rhs.prv))
      return false;
    if (__isset.nxt != rhs.__isset.nxt)
      return false;
    else if (__isset.nxt && !(nxt == rhs.nxt))
      return false;
    return true;
  }
  bool operator != (const t_job &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const t_job & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class t_hello {
 public:

  static const char* ascii_fingerprint; // = "7F21FB535884165D6350077C7B970E93";
  static const uint8_t binary_fingerprint[16]; // = {0x7F,0x21,0xFB,0x53,0x58,0x84,0x16,0x5D,0x63,0x50,0x07,0x7C,0x7B,0x97,0x0E,0x93};

  t_hello() : domain(""), name(""), is_master(0) {
  }

  virtual ~t_hello() throw() {}

  std::string domain;
  std::string name;
  bool is_master;

  bool operator == (const t_hello & rhs) const
  {
    if (!(domain == rhs.domain))
      return false;
    if (!(name == rhs.name))
      return false;
    if (!(is_master == rhs.is_master))
      return false;
    return true;
  }
  bool operator != (const t_hello &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const t_hello & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class t_route {
 public:

  static const char* ascii_fingerprint; // = "3628A1EB414F66736E1B2A082E79475F";
  static const uint8_t binary_fingerprint[16]; // = {0x36,0x28,0xA1,0xEB,0x41,0x4F,0x66,0x73,0x6E,0x1B,0x2A,0x08,0x2E,0x79,0x47,0x5F};

  t_route() : node_name(""), hops(0) {
  }

  virtual ~t_route() throw() {}

  std::string node_name;
  integer hops;

  bool operator == (const t_route & rhs) const
  {
    if (!(node_name == rhs.node_name))
      return false;
    if (!(hops == rhs.hops))
      return false;
    return true;
  }
  bool operator != (const t_route &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const t_route & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _e_routing__isset {
  _e_routing__isset() : msg(false) {}
  bool msg;
} _e_routing__isset;

class e_routing : public ::apache::thrift::TException {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  e_routing() : msg("") {
  }

  virtual ~e_routing() throw() {}

  std::string msg;

  _e_routing__isset __isset;

  bool operator == (const e_routing & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const e_routing &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const e_routing & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _e_job__isset {
  _e_job__isset() : msg(false) {}
  bool msg;
} _e_job__isset;

class e_job : public ::apache::thrift::TException {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  e_job() : msg("") {
  }

  virtual ~e_job() throw() {}

  std::string msg;

  _e_job__isset __isset;

  bool operator == (const e_job & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const e_job &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const e_job & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _e_node__isset {
  _e_node__isset() : msg(false) {}
  bool msg;
} _e_node__isset;

class e_node : public ::apache::thrift::TException {
 public:

  static const char* ascii_fingerprint; // = "EFB929595D312AC8F305D5A794CFEDA1";
  static const uint8_t binary_fingerprint[16]; // = {0xEF,0xB9,0x29,0x59,0x5D,0x31,0x2A,0xC8,0xF3,0x05,0xD5,0xA7,0x94,0xCF,0xED,0xA1};

  e_node() : msg("") {
  }

  virtual ~e_node() throw() {}

  std::string msg;

  _e_node__isset __isset;

  bool operator == (const e_node & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const e_node &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const e_node & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

} // namespace

#endif
