/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "model_constants.h"

namespace rpc {

const modelConstants g_model_constants;

modelConstants::modelConstants() {
}

} // namespace

