/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef model_CONSTANTS_H
#define model_CONSTANTS_H

#include "model_types.h"

namespace rpc {

class modelConstants {
 public:
  modelConstants();

};

extern const modelConstants g_model_constants;

} // namespace

#endif
